# Generated by Django 4.1.7 on 2023-02-28 22:33

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_data(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User(email="test@test.com", hashed_password=make_password('password'))

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
